name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: LEONELZANINELLI
          card: stats
          output_path: dist/stats.svg
          options: >-
            show_icons=true
            theme=transparent
            hide_border=true
            title_color=0b3c8a
            icon_color=0b3c8a
            text_color=c9d1d9

      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@master
        with:
          username: LEONELZANINELLI
          card: top-langs
          output_path: dist/top-langs.svg
          options: >-
            layout=compact
            theme=transparent
            hide_border=true
            title_color=0b3c8a
            text_color=c9d1d9

      - name: Publish Stats
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          keep_files: true
